### ISSUE TITLE
可否增加@一个微信，然后加一个移出 就T出群

### ISSUE THREAD

**Issue by haoxuexiaoyao** [TKkk-iOSer/WeChatPlugin-iOS#1]
已经完美安装运行，非常好用。
就是入群欢迎语这个好像是没有的自动欢迎。
另外比如有一个微信昵称为：今夜打老虎
@今夜打老虎 移出 就把这个人提出群呢 

类似微信机器人：https://github.com/LCTT/LCBot

**Comment by TKkk-iOSer** [comment]
1. 入群欢饮语无效么？
2. 提出群这个可以，就是最近忙，没有充足的时间搞这个了，估计要过段时间。我先记着。

**Comment by haoxuexiaoyao** [comment]
入群欢迎语测试了下，没有问题了。
踢出群的主要就是，比如指定哪几个微信好友为管理员，看到有人发违规信息，就可以手动@那个用户 加一个命令 踢出 期待这个有空你完成

**Comment by TKkk-iOSer** [comment]
懂了，就是省的去翻群成员列表，再删除。

**Comment by haoxuexiaoyao** [comment]
@TKkk-iOSer 对的哈 这样就可以多个群管理员可以看到违规的群成员 直接@后移出群
