### ISSUE TITLE
打包签名问题

### ISSUE THREAD

**Issue by Eivank** [TKkk-iOSer/WeChatPlugin-iOS#11]
打包完，安装失败，用的个人证书，我看了下，打包后ipa根目录没有plist文件，直接就是一个wechat.app

**Comment by Eivank** [comment]
我是个人证书，手机上已经有了一个签好，之前使用的，

**Comment by TKkk-iOSer** [comment]
个人证书的话，如果没有加入开发者计划，那么7天会过期。话说你使用我传的百度云的app文件么

**Comment by haoxuexiaoyao** [comment]
另外我用别人的证书的话，打包成功，无法安装

**Comment by TKkk-iOSer** [comment]
@haoxuexiaoyao 请保证证书、开发者、手机要匹配，不然没法安装成功的。虽然重签名可以。

**Comment by Eivank** [comment]
99一年的，我自己注入的

**Comment by Eivank** [comment]
越狱机器可以安装使用

**Comment by TKkk-iOSer** [comment]
你是重新make的么？是的话，clone一下再试一次。那个脚本只是简化了操作，可以去[TKTweakDemo](https://github.com/TKkk-iOSer/TKTweakDemo)按照操作重新来一次，看看有没有提示什么错误

**Comment by Eivank** [comment]
ttdeMacBook-Pro:Others tt$ otool -L other.dylib
other.dylib (architecture armv7):
	/Library/MobileSubstrate/DynamicLibraries/other.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.55.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1349.56.0)
	@loader_path/libsubstrate.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/System/Library/Frameworks/AdSupport.framework/AdSupport (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.7.47)
other.dylib (architecture arm64):
	/Library/MobileSubstrate/DynamicLibraries/other.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Foundation (compatibility version 300.0.0, current version 1349.55.0)
	/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation (compatibility version 150.0.0, current version 1349.56.0)
	@loader_path/libsubstrate.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.50.2)
	/System/Library/Frameworks/AdSupport.framework/AdSupport (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/UIKit.framework/UIKit (compatibility version 1.0.0, current version 3600.7.47)


问下，这个依赖检查好了，怎么看出来是那几个呢？？？

**Comment by TKkk-iOSer** [comment]
你不是已经替换成libsubstrate.dylib了么

**Comment by Eivank** [comment]
这个是另外的插件，我注入没效果，所以说怎么看依赖有哪些

**Comment by yinjialiang1993** [comment]
这边证书打入进去会出现
The executable was signed with invalid entitlements.
The entitlements specified in your application’s Code Signing Entitlements file are invalid, not permitted, or do not match those specified in your provisioning profile

目测是profile证书问题，profile证书需要什么特别的配置么？

**Comment by TKkk-iOSer** [comment]
@yinjialiang1993 这个是`iOS App Singer`提示的么？应该是证书问题，确保证书未过期，且证书跟开发者相匹配就行了。

**Comment by yinjialiang1993** [comment]
这个问题已经解决，证书这边的问题。 设置好 就OK

**Comment by colorfuljoe** [comment]
加入开发者计划要付费吗 ？

**Comment by TKkk-iOSer** [comment]
@colorfuljoe 需要
