### ISSUE TITLE
安装第一次是内部api有错,我又重新创建了一次,显示这个

### ISSUE THREAD

**Issue by ziyanziyu** [TKkk-iOSer/WeChatPlugin-iOS#12]
![image](https://user-images.githubusercontent.com/7148309/30156196-9bc47714-93f1-11e7-92cb-b9eccf8e3412.png)

**Comment by TKkk-iOSer** [comment]
是自己重新make的么？一般70%的问题都是证书跟开发者不匹配。

**Comment by ziyanziyu** [comment]
@TKkk-iOSer 不是重新make的,我下载的百度网盘的那个,证书用自己id生成的

**Comment by TKkk-iOSer** [comment]
1. 请仔细检查下证书跟开发者是否匹配…可以换个证书跟开发者试试。
2. 请确保证书已经安装在该手机上，可使用xcode 在真机上run一次。~~如何查看是否已安装证书→→![Devices.png](http://upload-images.jianshu.io/upload_images/965383-779ee64170495e9c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)~~

**Comment by ziyanziyu** [comment]
@TKkk-iOSer 和创建project时候选择应用类型有关系吗?我创建了单页面应用,然后生成临时证书重新签名后,出现内部api错误
![image](https://user-images.githubusercontent.com/7148309/30264080-ee254dba-9709-11e7-9af4-3c090f72a9d8.png)

**Comment by TKkk-iOSer** [comment]
应用类型没关系，之前我出现这个也有可能是证书的问题。如果安装了点击闪退的话那么除了证书问题外就有可能是手机内没有该证书。

**Comment by BigZhanghan** [comment]
修改源码后，执行make，并没有生成robot.dylib文件(之前的robot.dylib文件我删除掉了)。请问是咋回事啊？
![1505279281157](https://user-images.githubusercontent.com/18651714/30360552-bedfdfd4-9817-11e7-8bc2-f6c9ceddb3ff.jpg)

**Comment by TKkk-iOSer** [comment]
@BigZhanghan  https://github.com/TKkk-iOSer/WeChatPlugin-iOS/issues/10

**Comment by BigZhanghan** [comment]
@TKkk-iOSer 找到了，谢啦。
