### ISSUE TITLE
弱弱的问一句 微信的应用名称怎么修改

### ISSUE THREAD

**Issue by PotatoPudding** [TKkk-iOSer/WeChatPlugin-iOS#13]
弱弱的问一句 微信的应用名称怎么修改

**Comment by PotatoPudding** [comment]
修改Bundle display name 不起作用

**Comment by TKkk-iOSer** [comment]
这个的话倒是没试过，可以去 https://github.com/DanTheMan827/ios-app-signer/issues 看看
