### ISSUE TITLE
账号切换引起无限循环的自动回复

### ISSUE THREAD

**Issue by rokistar** [TKkk-iOSer/WeChatPlugin-iOS#14]
1. 顺利安装
2. 登录第一个账号
3. 设置个人自动回复
4. 退出账号
5. 登录第二个账号
6. 微信团队的公众号登录确认进入无限自动回复

**Comment by TKkk-iOSer** [comment]
求告知设置的自动回复关键字与内容

**Comment by TKkk-iOSer** [comment]
好吧，原来是iOS的，这个好像没有处理，之后在处理下…

**Comment by rokistar** [comment]
关键字：*
内容：山水有相逢
当切换到新账号的时候，微信团队会提示欢迎回来，然后触发了关键字的自动回复，自动回复后，微信团队自动回复问遇到什么问题？然后又一次触发自动回复，这样就进入循环。
微信团队公众号的循环回复问题只会出现在第一次切换到新账号登录后，关掉自动回复，重新登录则不会触发自动回复
如果在使用过程中，微信团队再一次发消失过来，同样会触发自动回复引起无限循环。
其他公众号的消息是否有同样问题，目前暂不清楚。
建议解决方法是，添加自动回复次数限制。

**Comment by TKkk-iOSer** [comment]
iOS 上面没有过滤掉公众号信息的自动回复，之后再屏蔽。

**Comment by TKkk-iOSer** [comment]
更新微信版本6.5.16 & 屏蔽公众号自动回复
