### ISSUE TITLE
请问，未越狱的手机可以使用吗？

### ISSUE THREAD

**Issue by face7hesun** [TKkk-iOSer/WeChatPlugin-iOS#18]
请问，未越狱的手机可以使用吗？

**Comment by TKkk-iOSer** [comment]
这个就是为未越狱的手机用的

**Comment by face7hesun** [comment]
真的非常感谢非常感谢，我手机上已经安装了微信，必须要先删掉，然后再安装吗？

**Comment by TKkk-iOSer** [comment]
不用，这个相当于是另一个新的微信

**Comment by face7hesun** [comment]
我用XCODE安装完微信后，微信一直无法连接到网络……

**Comment by TKkk-iOSer** [comment]
在蜂窝网络或者是wifi那里，把当前微信的数据开关打开。(~~应用列表会有2个微信，其中一个是注入插件的微信，两个都打开~~)

**Comment by face7hesun** [comment]
尴尬的是，数据是开着的。。微信主界面一直显示未连接，而且消息发送不出去。。

**Comment by TKkk-iOSer** [comment]
![WX20170919-121420@2x.png](http://upload-images.jianshu.io/upload_images/965383-dafd782464ef0074.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
我的意思是这个有打开么？如果有的话不行就先把微信全退了再试下，再不行重启下

**Comment by face7hesun** [comment]
这个功能我的确打开了
还有个问题是，在设置最下方，有两个微信，其中一个和您图中所示一样，另外一个微信，点进去后，只有“后台应用刷新”这功能的开关。

**Comment by face7hesun** [comment]
而且是，我在微信设置里，也没有看到“微信小助手”功能

**Comment by face7hesun** [comment]
谢谢， 找到问题了，原来重新生成了一个微信啊，并且要在描述文件里信任这个APP才可以使用。。
谢谢您了。。非常感谢出了这样的一篇文章，谢谢谢谢。

最后麻烦咨询一下，您文章中说签名只有7天时效，那么7天后失效的话，我需要按照文章操作，重新再安装一次APP吗？

**Comment by TKkk-iOSer** [comment]
哦，忘了这个描述文件了…之后我再补上。
另外7天是的，要重新安装。如果是有加入苹果开发者计划的，可以用一年。

**Comment by face7hesun** [comment]
我有苹果开发者账号。我们公司同事把我加进去的。

所以，我用开发者账号生成一个证书，并且用开发者账号生成的APP进行安装，那么就可以使用一年吗？

**Comment by TKkk-iOSer** [comment]
是的，可以用一年

**Comment by face7hesun** [comment]
OK，真的真的非常感谢

**Comment by face7hesun** [comment]
如果可以，我会打赏奖励，如果这里有通道的话。

**Comment by TKkk-iOSer** [comment]
哈哈哈，看来我是时候加入打赏功能了

**Comment by face7hesun** [comment]
哈哈，已经打赏完了。

不过，作者，可以帮忙更新一下6.5.17版本的微信吗？今天刚更新的，这个版本兼容了iOS11

**Comment by TKkk-iOSer** [comment]
我还以为是谁打赏了😂。我之后再传下，另外新系统的话可能会有问题，这个还不确定。 其余的可以去https://github.com/TKkk-iOSer/WeChatPlugin-iOS/issues/21 这个issue看看。

**Comment by face7hesun** [comment]
谢谢，我学习一下。实在难为我这个没学过开发的人，哈哈哈
