### ISSUE TITLE
2.3.2版本微信功能不兼容

### ISSUE THREAD

**Issue by cxk502401673** [TKkk-iOSer/WeChatPlugin-iOS#19]
2.3.2版本微信功能不兼容，大神更新下吧

**Comment by TKkk-iOSer** [comment]
？？？ iOS 版本？

**Comment by cxk502401673** [comment]
mac版的

**Comment by TKkk-iOSer** [comment]
可以的，我的是2.3.2的，请问是有什么问题？还有mac OS版本是10.11的么？

**Comment by cxk502401673** [comment]
os 10.11.6 (15G1611)   App Store下载的微信  自动回复开关一点微信就闪退了

**Comment by TKkk-iOSer** [comment]
下载一下这个，[WeChatPlugin-MacOS-develop](https://github.com/TKkk-iOSer/WeChatPlugin-MacOS/tree/develop)，看看还会不会崩溃。

**Comment by cxk502401673** [comment]
Ok  我试试看

**Comment by cxk502401673** [comment]
还是闪退了

**Comment by TKkk-iOSer** [comment]
先卸载再重装后还是闪退…这就尴尬了…有些API只有10.12才能用所以就崩了。

**Comment by cxk502401673** [comment]
其他功能都好
 就是自动回复 点设置闪退
 哈

**Comment by TKkk-iOSer** [comment]
远程控制呢

**Comment by cxk502401673** [comment]
远程控制我试了 退出qq  没问题 其他还没试

**Comment by cxk502401673** [comment]
远程控制没问题哈

**Comment by TKkk-iOSer** [comment]
push 了代码，重新点击上面的链接再安装下试试。

**Comment by cxk502401673** [comment]
自动回复可以了

**Comment by TKkk-iOSer** [comment]
ok，谢了，哈哈。真不容易

**Comment by cxk502401673** [comment]
😅ios的没开发者账号，好想弄一个装一装

**Comment by TKkk-iOSer** [comment]
去注册个苹果开发者账号就可以了，不过只能用7天，加入开发者计划可以用一年。
