### ISSUE TITLE
逆向小白的提问。

### ISSUE THREAD

**Issue by Wbqqqq** [TKkk-iOSer/WeChatPlugin-iOS#2]
按照你的步骤 随便创建了一个bundleid 也生成了 对应的证书  重签名也成功了  安装ipa怎么都安装不上  一直报错   是不是我哪里做错了。。

**Comment by TKkk-iOSer** [comment]
应该是证书问题。是用我传的百度云的app重签名的么？xcode创建bundleid的那个原app有用真机运行一遍么？

**Comment by Wbqqqq** [comment]
搞定啦 感谢作者  我自动创建的证书 我发现没有在开发者账号里 所以一直装不上 后来我在开发证书中 手动创建了一个 然后重签名就可以啦

**Comment by Wbqqqq** [comment]
额  小白我还有一个问题   既然我把你的ipa的bundleid都改了  为什么第三方登录 分享这些都能打开

**Comment by TKkk-iOSer** [comment]
你是说第三方登录，还是能够调用这个注入动态库的微信是么

**Comment by Wbqqqq** [comment]
是的  能调起 你这个重签名的微信  这是什么原理

**Comment by TKkk-iOSer** [comment]
* 首先需要知道的是，别人要调用自己的 app，是需要配置 `info.plist` 文件的`URL Types`,也就是说第三方是通过`URL Types`打开微信的；而 `info.plist` 保存在.app文件中而不是.ipa文件中。

* 其次，hook只是修改了.app文件里面的可执行二进制文件，并没有修改`info.plist`文件。而重签名只是在.app文件加个壳包装一下。所以还是可以调用的。

**Comment by Wbqqqq** [comment]
感谢作者答疑解惑 🙏
