### ISSUE TITLE
关于微信支付和微信分享问题

### ISSUE THREAD

**Issue by ge2009** [TKkk-iOSer/WeChatPlugin-iOS#20]
## 微信支付问题
在支付的时候会提示账号不安全不能进行支付

## 微信分享问题
在原来的微信还没删除的情况下，我们做了微信的一个分享，他会弹出默认的微信的应用而不是这个微信，不知道如果我把原来的微信删除后会不会出问题？

**Comment by TKkk-iOSer** [comment]
1. 请问微信支付的是在什么场景下的？美团支付么？我很少用这个去支付倒是没有发现…

2. 分享的话，确实把默认的微信删除就可以了，之后在安装默认的微信也行，不过这样默认的微信聊天记录以及里面的信息都会消失。

**Comment by ge2009** [comment]
是在扫微信二维码的时候，不过也有可能是我两个微信共存的情况下产生的，我等数据迁移完后，删除了再试下，多谢！

**Comment by TKkk-iOSer** [comment]
记住备份好数据，如果是用个人的证书的话，那么只能用7天，7天过后这个微信就打不开会闪退。需要重新安装

**Comment by ge2009** [comment]
嗯，我用的是企业的证书，是不是企业证书如果过期了，也会和个人证书一样的结果？

**Comment by TKkk-iOSer** [comment]
是的，如果过期的都一样。
