### ISSUE TITLE
微信更新了，如何获取到安装包呢？

### ISSUE THREAD

**Issue by face7hesun** [TKkk-iOSer/WeChatPlugin-iOS#21]
微信更新了，如何获取到安装包呢？
现在电脑上的iTunes里已经无法下载手机APP了……

**Comment by face7hesun** [comment]
我在pp助手上找到了新版微信，在签名时出现了这个问题：Error extracting ipa file

**Comment by face7hesun** [comment]
我把ipa扩展名改成了.app，结果提示：unsupported input file

**Comment by ycace** [comment]
https://github.com/TKkk-iOSer/WeChatPlugin-iOS/blob/master/README.md

**Comment by face7hesun** [comment]
这个页面里面，不是最新版安装包了。。目前微信最新版是6.5.17了

**Comment by face7hesun** [comment]
看来6.5.17版本的微信，还需要作者重新修改一下，才行吧。

6.5.17这个版本针对IOS11修复了很多不流畅和BUG问题，所以这个版本还是挺重要的

**Comment by TKkk-iOSer** [comment]
我之后在更新下6.5.17。
另外授人予鱼不如授人予渔，你也可以自己重新注入下，具体的教程readme有写，我简单叙述下：

1. 先去PP助手下载越狱版微信的ipa文件，将该文件重命名为wechat.ipa。（**一定要越狱版**）
2. 将下载完成的ipa微信放到项目中的`./Others` 文件夹中。
3. 打开终端，在当前目录中执行 `./Others/autoInsertDylib.sh ./Others/wechat.ipa ./Others/robot.dylib ` ，完成后即可以在项目目录中的`Products `文件夹中看到app文件。
4. 重签名获得注入的ipa文件。

**Comment by face7hesun** [comment]
谢谢，不过在PP助手里，貌似没有搜到“越狱版微信”，好像只有一个微信

如果您方便的话，能发一个链接我看一下吗？

**Comment by face7hesun** [comment]
找到了。谢谢，我说我电脑的PP助手里怎么搜不到，原来是要安装Windows版本的PP助手才可以啊？？？
我用的MAC

**Comment by TKkk-iOSer** [comment]
我是在macbook 的PP助手客户端里面下的。

![WX20170920-155943@2x.png](http://upload-images.jianshu.io/upload_images/965383-640889a4293b3bd1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by face7hesun** [comment]
谢谢谢谢。。
readme教程，您方便发一个链接吗？我……没找到。。

**Comment by TKkk-iOSer** [comment]
就是这个项目的首页内容 ---> https://github.com/TKkk-iOSer/WeChatPlugin-iOS

**Comment by TKkk-iOSer** [comment]
已上传6.5.17 @face7hesun

**Comment by face7hesun** [comment]
谢谢，不过我想自己尝试一次，这样的话，我以后就可以自己做了，非常感谢您的教程

**Comment by face7hesun** [comment]
-bash: /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/robot.dylib: Bad CPU type in executable

这一步貌似没通过啊？
而且我在readme.md里面看到的描述，好像和网页里写的签名教程一样~~

**Comment by face7hesun** [comment]
Last login: Wed Sep 20 17:07:04 on ttys003
EthandeMacBook-Pro:~ ethan$ /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/autoInsertDylib.sh 
mkdir: /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/../Products/: File exists
cp: fts_open: No such file or directory
开始注入dylib >>> \n\n\n
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/tweak-temp-tk/': Is a directory
unzip:  cannot find or open /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/tweak-temp-tk/, /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/tweak-temp-tk/.zip or /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/tweak-temp-tk/.ZIP.
ls: /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/extracted/Payload/: No such file or directory
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
/Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/extracted/Payload//: No such file or directory
注入成功 !!!
mv: rename /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/extracted/Payload//_patched to /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/extracted/Payload//: No such file or directory
cp: /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/extracted/Payload/: No such file or directory
EthandeMacBook-Pro:~ ethan$ /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/wechat.ipa 
-bash: /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/wechat.ipa: Permission denied
EthandeMacBook-Pro:~ ethan$ /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/robot.dylib 
-bash: /Users/ethan/Downloads/WeChatPlugin-iOS-master/Others/robot.dylib: Bad CPU type in executable

在products却没有APP

**Comment by TKkk-iOSer** [comment]
终端有切换到项目当前的文件夹么
