### ISSUE TITLE
大佬，啥时候加个抢红包的功能啊

### ISSUE THREAD

**Issue by PotatoPudding** [TKkk-iOSer/WeChatPlugin-iOS#22]
大佬，啥时候加个抢红包的功能啊

**Comment by PotatoPudding** [comment]
自己家 没加成功。。。

**Comment by TKkk-iOSer** [comment]
相信自己，你可以的。 

~~红包就不加了，https://github.com/TKkk-iOSer/WeChatPlugin-iOS/issues/15~~
