### ISSUE TITLE
自己打的最新的微信版本 6.5.18 有问题

### ISSUE THREAD

**Issue by redihd** [TKkk-iOSer/WeChatPlugin-iOS#26]
自动回复设置的*或者 任意关键字均无效 UI也有问题
最新的iOS 11.0.1 微信版本为6.5.18

**Comment by redihd** [comment]
试了一下iOS 11.0.0的
使用你提供的百度云的微信
自动回复与UI均无问题

**Comment by TKkk-iOSer** [comment]
好的，之后看下

**Comment by suisr9255** [comment]
使用的作者提供的百度云上的 6.5.17，iOS 11.0.1
UI无问题，自动回复无效，其他均正常

**Comment by TKkk-iOSer** [comment]
@suisr9255 能否描述下如何复现？比如关键字是什么？是否进入后台？隔了多长的时间？

**Comment by suisr9255** [comment]
@TKkk-iOSer 正常安装之后，无论是设置关键字匹配（*或者某个字符串）不根据关键词直接全部自动回复，均未生效，前后台均无效

**Comment by TKkk-iOSer** [comment]
关键词匹配是要完全一致才能触发自动回复的，为了防止误触发。@suisr9255
