### ISSUE TITLE
关于其他app分享至微信的问题

### ISSUE THREAD

**Issue by Dennestop** [TKkk-iOSer/WeChatPlugin-iOS#27]
您好！
当其他应用分享内容选择至微信的时候，如何可以选择到原生的app?
目前问题：无论分享任何东西至微信，系统会默认选择新安装的这个共存版。

非常感谢您的热心解答！

**Comment by TKkk-iOSer** [comment]
分享的话，之前测试是会默认选择先安装的微信，就比如说先安装了这个共存版再安装微信原版，那么分享的话会默认选中共存版；如果先安装了微信原版再安装共存版，那么分享会选中微信原版。
