### ISSUE TITLE
安装以后可以正常使用，但只要开启小助手就会闪退

### ISSUE THREAD

**Issue by colorfuljoe** [TKkk-iOSer/WeChatPlugin-iOS#28]
你好，我安装了你的App后，可以正常使用原本的功能，但只要一开启助手里的功能，就会闪退，再也无法进入app了。请问是怎么回事？谢谢 ！

刚给你打赏了27块 ，祝好 ^_^

**Comment by TKkk-iOSer** [comment]
谢谢，求告知 iOS系统版本、微信版本、iOS语言环境分别是什么？

另外目前小助手不支持英文版本，如果系统语言为英文，有人撤回消息会导致闪退。

**Comment by colorfuljoe** [comment]
非常感谢，我想我找到原因了，我的系统是英文界面。

请问能不能用这个方法安装多个微信呢 ？即让我的每个微信都可以用小助手 ？

**Comment by TKkk-iOSer** [comment]
可以，一个证书对应一个微信，相当于一个证书对应一个app。

**Comment by colorfuljoe** [comment]
明白了，感谢
