### ISSUE TITLE
安装失败问题

### ISSUE THREAD

**Issue by suisr9255** [TKkk-iOSer/WeChatPlugin-iOS#29]
进行重签名的时候选择修改包名出现一下错误
![error](https://user-images.githubusercontent.com/11376445/31307149-686aa044-ab90-11e7-8c5b-3c4f2941f5ae.png)
如果不选择修改包名，默认生成的包的报名仍然是com.tencent.xin，如果已经安装了appstore版本会导致安装失败，卸载后安装正常，但是想两个版本同时存在。。。

**Comment by suisr9255** [comment]
重新生成了一个 Explicit App ID 类型的provisioning profiles，就没问题了
难不成不能使用Wildcard App ID类型的profiles随便起个buddle id？

**Comment by TKkk-iOSer** [comment]
你是用`iOS APP Signer`重签名的么？是的话不用修改`App ID`，因为跟你选择的`Provisioning Profile`是一致的，所以要保证证书没问题，bundle id 要可以用。至于`App ID`的类型我倒是没有去研究过。

**Comment by suisr9255** [comment]
我是想改掉包名，不然的话会使用原始的的包名：com.tencent.xin，会覆盖原来的微信，无法实现多开

**Comment by TKkk-iOSer** [comment]
我倒是不会覆盖原版
