### ISSUE TITLE
有什么办法可以防止非官方检测吗？

### ISSUE THREAD

**Issue by kimpeng** [TKkk-iOSer/WeChatPlugin-iOS#34]
bundleId
clientSeqId
这些都试了，还是会被检测到

**Comment by Jeff-HOU** [comment]
我也是被检测到，刚刚解冻。
Type: Login blocked. Self-service unblock allowed.
Reason: Installed unofficial version of WeChat (uninstall immediately)

**Comment by TKkk-iOSer** [comment]
除了这两个外，想到的就是用户行为了，比如秒回什么的，这个目前没有进行处理。

**Comment by kimpeng** [comment]
我只是登录了什么都没做……

**Comment by TKkk-iOSer** [comment]
😂这么可怕…我用了这么久都没被检测到…使用的是哪个版本的微信？

**Comment by Jeff-HOU** [comment]
我的是6.5.17，刚用了一天

**Comment by kimpeng** [comment]
我用的是6.5.1
我登录的是刚注册没多久的号，而且一直被封，然后自助解封的号。

**Comment by Jeff-HOU** [comment]
我的也是刚注册

**Comment by TKkk-iOSer** [comment]
之前未使用该插件是否有被检测到？我使用了6.5.17跟6.5.18都一段时间了，没遇到过

**Comment by Jeff-HOU** [comment]
我没开插件，现在纯粹是当第二个微信用

**Comment by kimpeng** [comment]
我也是没有，只是重新签名安装了而已

**Comment by Jeff-HOU** [comment]
我觉得可能是微信也有一个类似于支付宝的“智能大脑”，检测用户行为。新注册的账号评级会比较低，监管就比较多，要是再用个盗版微信，就会有批量注册什么的影响到他们及其他用户？如果是老用户评级比较高的，就不太会管，用假的就用假的吧，反正也不会有游戏作弊影响到别人。

**Comment by kimpeng** [comment]
阁下分析的有道理，估计Owner用的不是小号所以说不会被检测。

**Comment by TKkk-iOSer** [comment]
@Jeff-HOU  应该是了，我其他的两个小号都是用了3、4年的。感觉微信一般也不会去检测，除非是像抢红包这样涉及到利益的才会被封号，目前身边有听到被封号的也只有是抢红包导致的了。

**Comment by lanjuzi** [comment]
猜测微信主要检测小号。
自己两个常用的号一直很稳定，装了两个微信，一个 6.5.2.34 一个 6.5.15.33。
