### ISSUE TITLE
安装iOS App Signer 导出的ipa 安装有问题

### ISSUE THREAD

**Issue by Josin22** [TKkk-iOSer/WeChatPlugin-iOS#39]
如图
![wx20171113-131806](https://user-images.githubusercontent.com/9657587/32710712-59a65812-c875-11e7-89e1-2ddee6738fbd.png)

**Comment by TKkk-iOSer** [comment]
报错提示的是，没有删除相关的watch文件夹，或者是证书bundle设置有问题。请查看相关issue。https://github.com/TKkk-iOSer/WeChatPlugin-iOS/issues/6 https://github.com/TKkk-iOSer/WeChatPlugin-iOS/issues/11
