### ISSUE TITLE
App installation failed

### ISSUE THREAD

**Issue by playscforever** [TKkk-iOSer/WeChatPlugin-iOS#42]

**Comment by playscforever** [comment]
iOS11.1.1 （15B150)  @TKkk-iOSer

**Comment by playscforever** [comment]
![image](https://user-images.githubusercontent.com/7533665/32884873-5d93a39a-ca81-11e7-91e4-a11d1500507d.png)

**Comment by TKkk-iOSer** [comment]
应该是证书不匹配的问题，请查看相关issue。https://github.com/TKkk-iOSer/WeChatPlugin-iOS/issues/6 https://github.com/TKkk-iOSer/WeChatPlugin-iOS/issues/11
