### ISSUE TITLE
最新版微信 机器人 自动加好友等功能调用方法失效

### ISSUE THREAD

**Issue by fakedestinyck** [TKkk-iOSer/WeChatPlugin-iOS#43]
您好，我在将dylib注入后，签名的时候没有问题，但是在给iPhoneX安装的时候，报错
`The application is not built for this device`.

尝试直接签名安装没有注入的版本，同样提示这个错误。

请问是不是因为最新版本的微信做了对iPhoneX不同的build，所以导致我从越狱iPhone （非X）上导出的版本无效？

如果是的话，请问大大有什么方法可以获得到iphoneX能用的ipa呢？谢谢！

**Comment by TKkk-iOSer** [comment]
应该是的，可以根据readme中的说明，去pp助手下载最新的微信ipa(需要支持iPhoneX)，然后重新注入试试。

**Comment by fakedestinyck** [comment]
@TKkk-iOSer 我去重新下了一个是能安装了，但是发现自动回复功能 还有游戏作弊功能全部不能用，不知道是为什么。自己重新make 了一下还是不能用，不知道这个是微信版本更新了的原因还是iPhone X的原因

**Comment by TKkk-iOSer** [comment]
行，我之后看下

**Comment by SuperDannyBoy** [comment]
@fakedestinyck 你好，请问你是执行`make Makefile`指令吗？我发现执行之后提示`make: Nothing to be done for `xxx/Github/WeChatPlugin-iOS/Makefile'.`。请问能否告知下？谢谢了。

**Comment by fakedestinyck** [comment]
@SuperDannyBoy 不是 直接`make`就行了

**Comment by SuperDannyBoy** [comment]
@fakedestinyck 能否留个联系方式交流下？需要cd到目录下make吗

**Comment by fakedestinyck** [comment]
@SuperDannyBoy 直接`cd`到你的`WeChatPlugin-iOS`目录下，然后terminal里面`make`就好了

**Comment by fakedestinyck** [comment]
Ummm 忘记close 了， 之前问题解决了，似乎是新版本微信调用的函数是AsyncOnAddMsg不是Message Return。。。
Close
