### ISSUE TITLE
你好,我遇到问题了

### ISSUE THREAD

**Issue by Joker-1991** [TKkk-iOSer/WeChatPlugin-iOS#46]
下载的最新的微信和最新的库, 但是界面是这样的
[界面图片](http://image.vittaspace.top/gallery-images/WechatIMG18.jpeg)
请问这是哪里操作有错误吗, 多谢:)

**Comment by fakedestinyck** [comment]
你和我一开始碰到的问题一样，需要代码里自己改一下界面的高度，然后重新make一下

**Comment by Joker-1991** [comment]
@fakedestinyck 好的, 稍后我试下,多谢:)

**Comment by TKkk-iOSer** [comment]
@fakedestinyck 厉害了
