### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GrapeFruitJun** [TKkk-iOSer/WeChatPlugin-iOS#6]
<img width="467" alt="2017-09-06 1 19 52" src="https://user-images.githubusercontent.com/16380804/30095690-b25b989a-9306-11e7-8f81-8f10be8b54fb.png">
<img width="439" alt="2017-09-06 1 20 06" src="https://user-images.githubusercontent.com/16380804/30095691-b29f823a-9306-11e7-934d-7ef488e50f23.png">

**Comment by GrapeFruitJun** [comment]
按照步骤来的，报这个错

**Comment by TKkk-iOSer** [comment]
是否根据百度云的那个app进行操作的？
1. 如果是的话那应该是证书问题，也就是证书跟开发者不匹配。
2. 如果不是，而是自己重新编译的话，那么有安装theos么？输入make的时候是否有提示错误？如果没提示错误，建议修改下dylib的名称，有的名称会重签名失败（~~就是这么玄学😂~~）。

**Comment by fz0** [comment]
我也遇到这个问题，看log目测是因为创建的通配app id没包含推送功能导致打包失败的
但是如果在开发者中心去创建非通配的app id会提示id不可用，通配的又不能启用推送
这该如何解决呢？

**Comment by Ossey** [comment]
# 解决方法:
- 1. 在`钥匙串访问->登录`中把所有以`iPhone Developer`开头的证书删除。
- 2. 在 finder 进入`~/Library/MobileDevice/Provisioning Profiles`文件夹，将文件夹中所有的文件删除。
重新运行你创建的项目，继续之前的操作即可解决。
