### ISSUE TITLE
希望添加一个自动抢红包的功能

### ISSUE THREAD

**Issue by xiaofu666** [TKkk-iOSer/WeChatPlugin-iOS#63]
年底了    来个自动抢红包的插件吧    大年福利一下    还有  6.6.0版本的微信小助手页面布局靠上了   应该是大神用的iPhone X手机   所以其他手机显示有问题

**Comment by TKkk-iOSer** [comment]
适配这个没有做…另外，年底了，微信检测更加严格了…如果想装抢红包的话，可以参考这个 [WeChatRedEnvelop](https://github.com/buginux/WeChatRedEnvelop)
