### ISSUE TITLE
老铁打算加自动抢红包么？？

### ISSUE THREAD

**Issue by wjg1101766085** [TKkk-iOSer/WeChatPlugin-iOS#71]
老铁打算加自动抢红包么？？

**Comment by TKkk-iOSer** [comment]
有个小伙子做了整合版的 [https://github.com/ljyKangaroo/Karo_WeChatPro](https://github.com/ljyKangaroo/Karo_WeChatPro)

**Comment by wjg1101766085** [comment]
![qq 20180131155041](https://user-images.githubusercontent.com/10476982/35611007-8e840f04-069e-11e8-996e-7ff91904d39e.jpg)


还有个问题。编译报错是什么操作啊？？
