### ISSUE TITLE
在iPhone X上显示异常

### ISSUE THREAD

**Issue by wjg1101766085** [TKkk-iOSer/WeChatPlugin-iOS#76]
上面有一块黑黢黢的区域。还不能滑动！！而且微信也不会推送消息提示了！！

![_20180227101024](https://user-images.githubusercontent.com/10476982/36706791-7e7d973e-1ba6-11e8-9220-a9db24e5e328.png)

**Comment by TKkk-iOSer** [comment]
iPhoneX没做适配，另外由于是个人证书，所以没有消息推送。
