### ISSUE TITLE
最新ipa安装完后闪退

### ISSUE THREAD

**Issue by SunboyGo** [TKkk-iOSer/WeChatPlugin-iOS#8]
Wechat 6.5.15.ipa 按照步骤，安装完毕后，打开闪退。

**Comment by Eivank** [comment]
是不是证书没签好

**Comment by TKkk-iOSer** [comment]
1. 一般是证书和开发者没有匹配，请确保匹配；
2. 请确保证书已经安装在该手机上，可使用xcode 在真机上run一次。~~如何查看是否已安装证书→→![Devices.png](http://upload-images.jianshu.io/upload_images/965383-779ee64170495e9c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)~~
