### ISSUE TITLE
请问页面布局出现问题，需要更改哪里？

### ISSUE THREAD

**Issue by uclort** [TKkk-iOSer/WeChatPlugin-iOS#83]
![pic](http://orw4ygcvy.bkt.clouddn.com/IMG_0399.PNG)
微信版本 6.6.1 机型 iPhone 7.

你好，请问怎么更改才可以正常呢？如果需要改代码是更改哪个类呢？

**Comment by Jacob-LJ** [comment]
邮件我已收到，祝你生活愉快。
