### ISSUE TITLE
防越狱、防外挂检测是怎么做的 

### ISSUE THREAD

**Issue by Musk66** [TKkk-iOSer/WeChatPlugin-iOS#9]
请问博主做防越狱、防外挂检测了吗，虽然微信没有钉钉那么严格，但是还是会有警告

**Comment by TKkk-iOSer** [comment]
警告？我倒是没遇到过…防越狱外挂，没有深究，只知道有的好像是根据bundleId来判断是否有外挂的，之前有加了bundleId的hook替换，然而有时候界面会出问题就给去了…很好奇钉钉的那个不会，不过钉钉的那个项目是用iosopendev的，我这个的是theos，不知道是不是这个的原因…
