### ISSUE TITLE
什么时候可以出一个自动抢红包的~

### ISSUE THREAD

**Issue by tuoxie15** [TKkk-iOSer/WeChatPlugin-iOS#98]
已经投食，虽然投的不多但也是意思意思，马上12月年底开年会了，要抢红包，希望能搞个这样的功能~之前有个抢红包的ios版本，但那个git失联了，旦那块出一个能抢红包的微信吧~期待ing...

**Comment by cuiyu8580** [comment]
我参考了一下网上的资料，写了一个项目，目前第一件事就是支持抢红包，来支持一下吧？

**Comment by Gensiss** [comment]
有没有整成功的？
我们建个群一起研究？
微信号Genesis-x
加我备注“红包插件”
