### ISSUE TITLE
有没有整成功的？ 我们建个群一起研究？

### ISSUE THREAD

**Issue by Gensiss** [TKkk-iOSer/WeChatPlugin-iOS#99]
微信号Genesis-x 
加我备注“红包插件”

**Comment by DKJone** [comment]
@Gensiss  我在[WeChatRedEnvelop](https://github.com/buginux/WeChatRedEnvelop)咋也看到你了，我建了个新[项目地址](https://github.com/DKWechatHelper/DKWechatHelper)
![img_0223](https://user-images.githubusercontent.com/15855089/51583739-daa7a800-1f0c-11e9-983d-e61f425fbae3.jpg)

**Comment by Gensiss** [comment]
@DKJone 哈哈哈  加群啊

**Comment by Guodadada** [comment]
iOS 逆向开发交流
![21548900941_ pic](https://user-images.githubusercontent.com/16527069/52028150-df8ddc80-2548-11e9-9d0e-bb83ddf7411d.jpg)

**Comment by Gensiss** [comment]
![default](https://user-images.githubusercontent.com/16629478/52038491-740a3600-256d-11e9-9622-b1aa1858f6c9.png)

**Comment by x1917166** [comment]
> ![default](https://user-images.githubusercontent.com/16629478/52038491-740a3600-256d-11e9-9622-b1aa1858f6c9.png)
> 
>

**Comment by x1917166** [comment]
二维码失效了
